# Generated by Django 4.2.26 on 2025-11-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Двуместный люкс, Президентский сюит', max_length=255, verbose_name='Название номера')),
                ('description', models.TextField(help_text='Подробное описание удобств номера', verbose_name='Описание удобств')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях за одну ночь', max_digits=10, verbose_name='Цена за ночь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Номер отеля',
                'verbose_name_plural': 'Номера отеля',
                'db_table': 'rooms_room',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['price'], name='idx_rooms_price'), models.Index(fields=['created_at'], name='idx_rooms_created_at'), models.Index(fields=['name'], name='idx_rooms_name')],
            },
        ),
    ]
