# Generated by Django 4.2.26 on 2025-11-24 11:26

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        help_text="Дата заезда (формат: YYYY-MM-DD)",
                        verbose_name="Дата начала",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        help_text="Дата выезда (формат: YYYY-MM-DD)",
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания брони"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="rooms.room",
                        verbose_name="Номер отеля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "db_table": "bookings_booking",
                "ordering": ["date_start"],
                "indexes": [
                    models.Index(
                        fields=["room", "date_start", "date_end"],
                        name="idx_bookings_room_dates",
                    ),
                    models.Index(fields=["date_start"], name="idx_bookings_date_start"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("date_end__gt", models.F("date_start"))),
                name="check_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("date_start__gte", datetime.date(2025, 11, 24))),
                name="check_not_past_dates",
            ),
        ),
    ]
